[2021-02-06 06:42:47,057] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [queued]>
[2021-02-06 06:42:47,068] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [queued]>
[2021-02-06 06:42:47,068] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-06 06:42:47,068] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-06 06:42:47,068] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-06 06:42:47,073] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-02-04T00:00:00+00:00
[2021-02-06 06:42:47,077] {standard_task_runner.py:52} INFO - Started process 97 to run task
[2021-02-06 06:42:47,079] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2021-02-04T00:00:00+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp74h_iid9', '--error-file', '/tmp/tmp5l4lerir']
[2021-02-06 06:42:47,079] {standard_task_runner.py:77} INFO - Job 19: Subtask run_after_loop
[2021-02-06 06:42:47,112] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [running]> on host 6be8c7a30c6f
[2021-02-06 06:42:47,150] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-02-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-04T00:00:00+00:00
[2021-02-06 06:42:47,150] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-06 06:42:47,151] {bash.py:158} INFO - Running command: echo 1
[2021-02-06 06:42:47,158] {bash.py:169} INFO - Output:
[2021-02-06 06:42:47,159] {bash.py:173} INFO - 1
[2021-02-06 06:42:47,159] {bash.py:177} INFO - Command exited with return code 0
[2021-02-06 06:42:47,184] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20210204T000000, start_date=20210206T064247, end_date=20210206T064247
[2021-02-06 06:42:47,211] {taskinstance.py:1219} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-06 06:42:47,250] {local_task_job.py:146} INFO - Task exited with return code 0
