[2021-02-06 13:21:19,128] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [queued]>
[2021-02-06 13:21:19,138] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [queued]>
[2021-02-06 13:21:19,138] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-06 13:21:19,139] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-06 13:21:19,139] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-06 13:21:19,151] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-02-04T00:00:00+00:00
[2021-02-06 13:21:19,156] {standard_task_runner.py:52} INFO - Started process 82 to run task
[2021-02-06 13:21:19,159] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2021-02-04T00:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpeydkgmxh', '--error-file', '/tmp/tmpjpzl83ic']
[2021-02-06 13:21:19,159] {standard_task_runner.py:77} INFO - Job 10: Subtask run_after_loop
[2021-02-06 13:21:19,191] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2021-02-04T00:00:00+00:00 [running]> on host 66bc8b98f452
[2021-02-06 13:21:19,224] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-02-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-04T00:00:00+00:00
[2021-02-06 13:21:19,225] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-06 13:21:19,225] {bash.py:158} INFO - Running command: echo 1
[2021-02-06 13:21:19,233] {bash.py:169} INFO - Output:
[2021-02-06 13:21:19,234] {bash.py:173} INFO - 1
[2021-02-06 13:21:19,234] {bash.py:177} INFO - Command exited with return code 0
[2021-02-06 13:21:19,255] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20210204T000000, start_date=20210206T132119, end_date=20210206T132119
[2021-02-06 13:21:19,282] {taskinstance.py:1219} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-06 13:21:19,290] {local_task_job.py:146} INFO - Task exited with return code 0
